#!/usr/bin/env python3

"""
PROGRAM: tunneling_map.py
AUTHOR:          Alysse Weigand
CONTRIBUTORS:    Conceptual design, purpose, and validation by Alysse Weigand.
                 Code implementation and structure assisted by Claude (Anthropic),
                 April 2026.
LAST MODIFIED:   April 25, 2026


2D WKB Tunnelling Correction and Reaction Rate Calculator
==========================================================

Overview
--------
This script computes quantum-mechanical tunnelling corrections and
thermal rate constants for double proton transfer in a guanine–cytosine
(G–C) base pair, using the full two-dimensional potential energy surface
(2D PES) generated by ``generate_2d_pes.py``.

The calculation proceeds through four major stages:

  1. **Surface preparation** — Load the 2D PES grid, apply optional
     Gaussian smoothing, and construct a bicubic spline interpolant for
     smooth gradient evaluation.

  2. **Critical-point analysis** — Locate the canonical and tautomeric
     minima via L-BFGS-B optimisation on the interpolated surface, and
     find the saddle point by scanning curved connecting paths.

  3. **Path optimisation** — Compute two types of tunnelling path:

     *Minimum Energy Path (MEP)* via the simplified string method
     (project the gradient perpendicular to the path tangent, then
     redistribute images at equal arc-length spacing).

     *Minimal Action Path (MAP)* via free-node variational optimisation
     of the WKB action integral.  The path is represented as a chain of
     freely movable interior nodes, and L-BFGS-B finds the node
     configuration that minimises the semiclassical action.  Forward and
     reverse MAP paths are optimised independently, each with a
     self-consistent barrier iteration (the incident energy used to seed
     the search must match the barrier extracted from the converged
     path).

  4. **Rate calculation** — For each path (MEP and MAP, forward and
     reverse), numerically integrate the WKB transmission coefficient
     T(E) over a Boltzmann-weighted energy grid to obtain the tunnelling
     correction factor κ(T), then compute tunnelling-corrected Eyring
     rate constants k(T) = κ · (k_B T / h) · exp(−ΔV / k_B T).


Key Design Decisions
--------------------
- **MEP independence**: The MAP calculation does not depend on the MEP
  for its barrier height.  The initial barrier guess comes from a
  straight-line path.  The MEP geometry is used only as one of several
  initial guesses for the node optimiser (alongside straight-line and
  curved seeds); it seeds the search but does not constrain it.

- **Directional independence**: Forward (canonical → tautomeric) and
  reverse (tautomeric → canonical) MAP paths, barriers, and κ values
  are computed entirely independently.  The forward and reverse paths
  may differ from each other and from the MEP.

- **Self-consistent barrier**: Because the MAP path depends on the
  incident energy and the barrier depends on the resulting path, an SCF
  loop iterates the barrier until it converges (default tolerance
  1×10⁻⁴ eV).

- **Parallelism**: The temperature sweep and per-energy MAP
  optimisations can be distributed across multiple processes via
  ``--n-workers``.  Each worker rebuilds the spline from raw arrays to
  avoid pickling issues.


Comparison with 1D
------------------
A companion 1D script fits an Eckart barrier to the MEP profile and
integrates along a single reaction coordinate.  This 2D script instead
operates on the full surface, allowing the tunnelling path to deviate
from the MEP and exploit regions of lower action that are inaccessible
in the 1D treatment.  The MAP may cut corners on the surface, producing
a shorter path through a higher-potential but narrower barrier.


Output Files
------------
All outputs are written to the ``--grid-dir`` directory::

    2d_mep_analysis.png             MEP on contour surface + energy profile
    2d_mep_vs_MAP.png               MEP and MAP paths overlaid on PES
    2d_energy_mep_vs_MAP.png        Energy profiles along MEP and both MAPs
    2d_WKB_Tunnelling_forward.png   T(E) and T(E)·exp(−βE) for forward rxn
    2d_WKB_Tunnelling_reverse.png   Same for reverse reaction
    2d_action_difference_fwd.png    S_MEP(E) vs S_MAP(E), forward
    2d_action_difference_rev.png    Same for reverse
    2d_WKB_eyring_rates_fwd.png     Arrhenius plot, forward MEP vs MAP
    2d_WKB_eyring_rates_rev.png     Same for reverse
    2d_WKB_rates_vs_temperature.csv Full numerical data (κ, k, all T)


Dependencies
------------
  - Python 3.6+
  - NumPy, SciPy, Matplotlib, pandas
  - ``energies_eV.npy``, ``d1_values.npy``, ``d2_values.npy`` from
    ``generate_2d_pes.py collect``


Usage
-----
::

    # Basic run at 298.15 K (default)
    python tunneling_map.py --grid-dir 2d_pes_grid -T 298.15

    # Parallel run with 8 workers
    python tunneling_map.py --grid-dir 2d_pes_grid -T 298.15 --n-workers 8

    # Finer MAP discretisation and tighter SCF convergence
    python tunneling_map.py --grid-dir 2d_pes_grid --n-inst-nodes 48 --map-scf-tol 1e-5


Adapting to Other Systems
-------------------------
This script is system-agnostic — it operates on whatever 2D PES is
stored in the ``.npy`` files.  To apply it to a different double proton
transfer or any other two-coordinate reaction:

  1. Generate the 2D PES with ``generate_2d_pes.py`` (or any tool that
     produces the same ``.npy`` format).
  2. Adjust ``--smooth`` if the raw surface has significant noise.
  3. Adjust ``--mass-factor`` if the tunnelling particle is not a single
     proton (e.g., 2.0 for deuterium).
"""

import argparse
import numpy as np
from scipy import interpolate, optimize
from scipy.ndimage import gaussian_filter
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd
import multiprocessing as mp
from functools import partial

# ============================================================
# PHYSICAL CONSTANTS
# ============================================================
# Two sets of units are maintained: eV-based (for the PES, which is
# stored in eV) and SI (for the Eyring equation, which uses J/mol).

KB        = 8.617333262e-5      # Boltzmann constant (eV/K)
KB_J      = 1.380649e-23        # Boltzmann constant (J/K)
H_EV      = 4.135667696e-15     # Planck constant (eV·s)
H_J       = 6.62607015e-34      # Planck constant (J·s)
HBAR      = 6.582119569e-16     # ħ = h/2π (eV·s)
R_J       = 8.314462618         # Gas constant (J/mol·K)
EV_TO_J_MOL = 96485.3321        # 1 eV per particle → J/mol (= Faraday const.)

# --- Mass unit conversion ---
# The WKB action integral uses mass in eV·s²/Å² so that all terms
# in the integrand (√[2m(V−E)/ħ²] · ds) are dimensionally consistent
# when V is in eV and ds is in Å.
AMU_KG        = 1.66054e-27     # 1 atomic mass unit in kg
J_TO_EV       = 1.60218e-19     # 1 eV in Joules
ANG_TO_M      = 1e-10           # 1 Ångström in metres
AMU_TO_EVS2A2 = AMU_KG * ANG_TO_M**2 / J_TO_EV  # AMU → eV·s²/Å²
M_PROTON      = 1.00728 * AMU_TO_EVS2A2           # Proton mass in eV·s²/Å²

# --- Temperature sweep range ---
T_RANGE = (200, 400)   # K, for the Arrhenius / rate-vs-T plots
N_TEMPS = 100           # Number of temperature points in the sweep

# ============================================================
# CLI
# ============================================================
def parse_args():
    parser = argparse.ArgumentParser(
        description='2D WKB tunnelling correction calculator',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('--grid-dir', type=str, required=True,
                        help='Directory containing .npy files')
    parser.add_argument('-T', dest='T_REPORT', type=float, default=298.15,
                        help='Reporting temperature (K)')
    parser.add_argument('--smooth', type=float, default=0.3,
                        help='Gaussian smoothing sigma (0 = none)')
    parser.add_argument('--n-inst-nodes', type=int, default=24,
                        help='Number of free nodes for MAP '
                             '(excluding fixed endpoints)')
    parser.add_argument('--mass-factor', type=float, default=1.0,
                        help='Effective mass multiplier (1.0 = single proton)')
    parser.add_argument('--map-scf-tol', type=float, default=1e-4,
                        help='Convergence tolerance (eV) for self-consistent '
                             'MAP barrier iteration')
    parser.add_argument('--map-scf-maxiter', type=int, default=10,
                        help='Maximum iterations for self-consistent '
                             'MAP barrier search')
    parser.add_argument('--n-workers', type=int, default=1,
                        help='Number of parallel workers for κ integration '
                             '(1 = serial, >1 = multiprocessing)')
    return parser.parse_args()


# ============================================================
# 1. LOAD AND INTERPOLATE 2D PES
# ============================================================
def load_pes(grid_dir, smooth_sigma=0.3):
    """
    Load the 2D PES from NumPy arrays and build a smooth interpolant.

    Optional Gaussian smoothing (controlled by ``smooth_sigma``) reduces
    noise from incomplete SCF convergence or sparse grid regions without
    shifting the locations of stationary points appreciably.

    Parameters
    ----------
    grid_dir : str
        Directory containing ``d1_values.npy``, ``d2_values.npy``, and
        ``energies_eV.npy`` (produced by ``generate_2d_pes.py collect``).
    smooth_sigma : float
        Standard deviation (in grid-point units) for the Gaussian filter.
        Set to 0 to skip smoothing entirely.

    Returns
    -------
    d1, d2 : ndarray
        1-D scan coordinate arrays (Å).
    energies : ndarray
        Raw (unsmoothed) 2D energy surface (eV).
    energies_smooth : ndarray
        Smoothed energy surface (eV).
    spline : RectBivariateSpline
        Bicubic spline interpolant of the smoothed surface.
    """
    d1 = np.load(f"{grid_dir}/d1_values.npy")
    d2 = np.load(f"{grid_dir}/d2_values.npy")
    energies = np.load(f"{grid_dir}/energies_eV.npy")

    if smooth_sigma > 0:
        energies_smooth = gaussian_filter(energies, sigma=smooth_sigma)
    else:
        energies_smooth = energies.copy()

    spline = interpolate.RectBivariateSpline(d1, d2, energies_smooth, kx=3, ky=3)

    return d1, d2, energies, energies_smooth, spline


def _rebuild_spline(d1, d2, energies_smooth):
    """
    Reconstruct the bicubic spline from raw arrays.

    This exists because ``RectBivariateSpline`` objects cannot be pickled
    for ``multiprocessing``.  Each worker process calls this function to
    build its own local spline from the serialisable NumPy arrays.
    """
    return interpolate.RectBivariateSpline(d1, d2, energies_smooth, kx=3, ky=3)


def get_energy(spline, x1, x2):
    """
    Evaluate the interpolated potential energy at a single (d₁, d₂) point.

    Wrapper around ``RectBivariateSpline.__call__`` with ``grid=False``
    to return a scalar rather than a 2D array.
    """
    return float(spline(x1, x2, grid=False))


# ============================================================
# 2. FIND CANONICAL AND TAUTOMER MINIMAS
#       FIND SADDLE POINT FOR MEP
# ============================================================
def find_minimum(spline, d1, d2, initial_guess, label="minimum"):
    """
    Locate a local minimum on the interpolated 2D surface.

    Uses L-BFGS-B with bounds slightly inset from the grid edges to
    prevent the optimiser from running off the spline domain.

    Parameters
    ----------
    spline : RectBivariateSpline
        Interpolated PES.
    d1, d2 : ndarray
        1-D coordinate arrays (used only to set bounds).
    initial_guess : array-like, shape (2,)
        Starting (d₁, d₂) for the search.
    label : str
        Descriptive name (for logging only).

    Returns
    -------
    position : ndarray, shape (2,)
        Optimised (d₁, d₂) of the minimum.
    energy : float
        Energy at the minimum (eV).
    """
    bounds = [(d1[0] + 0.01, d1[-1] - 0.01),
              (d2[0] + 0.01, d2[-1] - 0.01)]

    result = optimize.minimize(
        lambda xy: get_energy(spline, xy[0], xy[1]),
        initial_guess,
        method='L-BFGS-B',
        bounds=bounds
    )

    if result.success:
        return result.x, result.fun
    else:
        E = get_energy(spline, initial_guess[0], initial_guess[1])
        return np.array(initial_guess), E


def find_saddle_point(spline, d1, d2, canonical_pos, tautomeric_pos, n_search=200):
    """
    Estimate the transition-state saddle point between two minima.

    Strategy: generate a family of curved paths connecting the canonical
    and tautomeric minima (parameterised by a scalar curvature offset
    along the perpendicular direction).  For each path, find the energy
    maximum.  The saddle point is the *lowest* such maximum across all
    paths — i.e., the minimax point.

    This is a heuristic search, not a true saddle-point optimisation
    (e.g., dimer or partitioned rational function).  It works well on
    smooth 2D surfaces with a single transition state between two minima.

    Parameters
    ----------
    spline : RectBivariateSpline
        Interpolated PES.
    d1, d2 : ndarray
        1-D coordinate arrays (used for boundary checking).
    canonical_pos, tautomeric_pos : ndarray, shape (2,)
        Positions of the two minima.
    n_search : int
        Number of curvature values to scan (more = finer search).

    Returns
    -------
    saddle_pos : ndarray, shape (2,)
        Estimated saddle-point coordinates.
    saddle_E : float
        Energy at the saddle point (eV).
    """
    best_saddle_E = np.inf
    best_saddle_pos = None

    curvatures = np.linspace(-0.4, 0.4, n_search)
    start = canonical_pos
    end = tautomeric_pos
    perp = np.array([-(end[1] - start[1]), end[0] - start[0]])
    perp = perp / np.linalg.norm(perp)

    for curv in curvatures:
        t_vals = np.linspace(0, 1, 200)
        path = np.array([
            start + t * (end - start) + curv * np.sin(np.pi * t) * perp
            for t in t_vals
        ])

        if (path[:, 0].min() < d1[0] or path[:, 0].max() > d1[-1] or
            path[:, 1].min() < d2[0] or path[:, 1].max() > d2[-1]):
            continue

        energies_path = np.array([get_energy(spline, p[0], p[1]) for p in path])
        max_idx = np.argmax(energies_path)
        max_E = energies_path[max_idx]

        if max_E < best_saddle_E:
            best_saddle_E = max_E
            best_saddle_pos = path[max_idx]

    return best_saddle_pos, best_saddle_E


# ============================================================
# 3. FIND MINIMUM ENERGY PATH (MEP) — STRING METHOD
# ============================================================
def find_mep(spline, d1, d2, canonical_pos, tautomeric_pos, n_images=100):
    """
    Find the Minimum Energy Path (MEP) using the simplified string method.

    The string method represents the path as a chain of images
    (discretisation points) and evolves them by:

      1. Computing the energy gradient at each interior image.
      2. Projecting out the component along the path tangent (so images
         move only perpendicular to the path, toward lower energy).
      3. Redistributing images at equal arc-length spacing to prevent
         them from clustering near the minima.

    Iteration continues until the maximum perpendicular step falls
    below 10⁻⁶ Å (or 500 iterations, whichever comes first).

    Parameters
    ----------
    spline : RectBivariateSpline
        Interpolated PES.
    d1, d2 : ndarray
        1-D coordinate arrays (for boundary clipping).
    canonical_pos, tautomeric_pos : ndarray, shape (2,)
        Fixed endpoints of the path.
    n_images : int
        Number of discretisation points along the path.

    Returns
    -------
    path : ndarray, shape (n_images, 2)
        Converged MEP coordinates.
    energies_along : ndarray, shape (n_images,)
        Energy at each image (eV).
    arc_lengths : ndarray, shape (n_images,)
        Cumulative arc length from the first image (Å).
    """
    start = canonical_pos.copy()
    end = tautomeric_pos.copy()

    path = np.array([start + t * (end - start)
                     for t in np.linspace(0, 1, n_images)])

    ds = 0.001
    for iteration in range(500):
        new_path = path.copy()
        max_move = 0

        for i in range(1, n_images - 1):
            tangent = path[i+1] - path[i-1]
            norm = np.linalg.norm(tangent)
            if norm < 1e-10:
                continue
            tangent = tangent / norm

            E0 = get_energy(spline, path[i, 0], path[i, 1])
            dEdx1 = (get_energy(spline, path[i, 0] + ds, path[i, 1]) - E0) / ds
            dEdx2 = (get_energy(spline, path[i, 0], path[i, 1] + ds) - E0) / ds
            grad = np.array([dEdx1, dEdx2])

            grad_perp = grad - np.dot(grad, tangent) * tangent
            step = 0.003 * grad_perp
            new_path[i] -= step
            max_move = max(max_move, np.linalg.norm(step))

            new_path[i, 0] = np.clip(new_path[i, 0], d1[0] + 0.01, d1[-1] - 0.01)
            new_path[i, 1] = np.clip(new_path[i, 1], d2[0] + 0.01, d2[-1] - 0.01)

        # Redistribute evenly
        diffs = np.diff(new_path, axis=0)
        seg_lengths = np.sqrt(np.sum(diffs**2, axis=1))
        cum_lengths = np.concatenate([[0], np.cumsum(seg_lengths)])
        total_length = cum_lengths[-1]

        if total_length < 1e-10:
            break

        even_s = np.linspace(0, total_length, n_images)
        path_x1 = np.interp(even_s, cum_lengths, new_path[:, 0])
        path_x2 = np.interp(even_s, cum_lengths, new_path[:, 1])
        path = np.column_stack([path_x1, path_x2])

        path[0] = start
        path[-1] = end

        if max_move < 1e-6 and iteration > 50:
            break

    energies_along = np.array([get_energy(spline, p[0], p[1]) for p in path])
    seg_lengths = np.sqrt(np.sum(np.diff(path, axis=0)**2, axis=1))
    arc_lengths = np.concatenate([[0], np.cumsum(seg_lengths)])

    return path, energies_along, arc_lengths


# ============================================================
# 4. MINIMAL ACTION PATH (MAP) CALCULATION
# ============================================================
def _nodes_to_path(nodes_flat, start, end, n_interp=200):
    """
    Convert a flat array of free-node coordinates into a dense path.

    The MAP path is parameterised by a small number of movable interior
    nodes (typically 24).  This function inserts the fixed endpoints,
    computes cumulative arc length along the node chain, and then
    linearly interpolates to produce a uniformly sampled dense path
    suitable for numerical integration of the WKB action.

    Parameters
    ----------
    nodes_flat : ndarray, shape (2*N_free,)
        Flattened coordinates [d1_1, d2_1, d1_2, d2_2, ...] of the
        free interior nodes.
    start, end : ndarray, shape (2,)
        Fixed path endpoints (canonical and tautomeric minima).
    n_interp : int
        Number of points in the output dense path.

    Returns
    -------
    ndarray, shape (n_interp, 2)
        Dense path coordinates.
    """
    n_free = len(nodes_flat) // 2
    all_nodes = np.zeros((n_free + 2, 2))
    all_nodes[0] = start
    all_nodes[-1] = end
    all_nodes[1:-1] = nodes_flat.reshape(n_free, 2)

    diffs = np.diff(all_nodes, axis=0)
    seg_lengths = np.sqrt(np.sum(diffs**2, axis=1))
    cum_s = np.concatenate([[0], np.cumsum(seg_lengths)])
    total_s = cum_s[-1]

    if total_s < 1e-12:
        return np.array([start + t * (end - start)
                         for t in np.linspace(0, 1, n_interp)])

    s_dense = np.linspace(0, total_s, n_interp)
    path_d1 = np.interp(s_dense, cum_s, all_nodes[:, 0])
    path_d2 = np.interp(s_dense, cum_s, all_nodes[:, 1])

    return np.column_stack([path_d1, path_d2])


def _action_objective(nodes_flat, start, end, spline, E_incident, mass,
                      d1_bounds, d2_bounds, penalty_weight=100.0):
    """
    Objective function for MAP optimisation: WKB action + boundary penalty.

    The WKB action integral is computed along the dense path defined by
    the free nodes.  A soft quadratic penalty is added for any node that
    strays outside the PES grid bounds, steering the optimiser back
    inward without hard constraints (which L-BFGS-B handles less
    efficiently for this problem).

    Parameters
    ----------
    nodes_flat : ndarray
        Flattened free-node coordinates (optimisation variables).
    start, end : ndarray
        Fixed endpoints.
    spline : RectBivariateSpline
        Interpolated PES.
    E_incident : float
        Incident (test) energy for the WKB integrand (eV).
    mass : float
        Effective tunnelling mass (eV·s²/Å²).
    d1_bounds, d2_bounds : tuple of (float, float)
        Allowed coordinate ranges.
    penalty_weight : float
        Stiffness of the boundary penalty.

    Returns
    -------
    float
        Action + penalty (dimensionless).
    """
    n_free = len(nodes_flat) // 2
    nodes = nodes_flat.reshape(n_free, 2)

    penalty = 0.0
    for nd in nodes:
        if nd[0] < d1_bounds[0]:
            penalty += penalty_weight * (d1_bounds[0] - nd[0])**2
        if nd[0] > d1_bounds[1]:
            penalty += penalty_weight * (nd[0] - d1_bounds[1])**2
        if nd[1] < d2_bounds[0]:
            penalty += penalty_weight * (d2_bounds[0] - nd[1])**2
        if nd[1] > d2_bounds[1]:
            penalty += penalty_weight * (nd[1] - d2_bounds[1])**2

    path = _nodes_to_path(nodes_flat, start, end, n_interp=200)
    action = compute_action(path, spline, E_incident, mass)

    return action + penalty


def find_instanton_variational(spline, d1, d2, canonical_pos, tautomeric_pos,
                                E_incident, mass, n_free_nodes=24,
                                mep_path=None):
    """
    Find the optimal tunnelling path by minimising the
    WKB action over all free node positions.

    The path is represented as n_free_nodes movable interior points
    between the fixed canonical and tautomeric endpoints. Each node
    has two degrees of freedom (d1, d2), giving 2*n_free_nodes total
    parameters. scipy.optimize.minimize (L-BFGS-B) is used to find
    the configuration that minimises the WKB action integral.

    Multiple initial conditions are tested:
      1. Straight-line (concerted diagonal)
      2. Two curved initialisations (biased toward each stepwise corner)
      3. MEP-seeded (if mep_path is provided)
    The best result across all initialisations is returned.
    """
    start = canonical_pos
    end = tautomeric_pos
    d1_bounds = (d1[0] + 0.005, d1[-1] - 0.005)
    d2_bounds = (d2[0] + 0.005, d2[-1] - 0.005)

    bounds = []
    for _ in range(n_free_nodes):
        bounds.append(d1_bounds)
        bounds.append(d2_bounds)

    initial_guesses = []

    t_nodes = np.linspace(0, 1, n_free_nodes + 2)[1:-1]
    straight_nodes = np.array([start + t * (end - start) for t in t_nodes])
    initial_guesses.append(('straight', straight_nodes.flatten()))

    perp = np.array([-(end[1] - start[1]), end[0] - start[0]])
    norm_perp = np.linalg.norm(perp)
    if norm_perp > 0:
        perp = perp / norm_perp
    for curv, label in [(0.15, 'curve_pos'), (-0.15, 'curve_neg')]:
        curved_nodes = np.array([
            start + t * (end - start) + curv * np.sin(np.pi * t) * perp
            for t in t_nodes
        ])
        curved_nodes[:, 0] = np.clip(curved_nodes[:, 0], d1_bounds[0], d1_bounds[1])
        curved_nodes[:, 1] = np.clip(curved_nodes[:, 1], d2_bounds[0], d2_bounds[1])
        initial_guesses.append((label, curved_nodes.flatten()))

    # 3. MEP-seeded initialisation (if provided)
    if mep_path is not None and len(mep_path) > 2:
        mep_diffs = np.diff(mep_path, axis=0)
        mep_seg = np.sqrt(np.sum(mep_diffs**2, axis=1))
        mep_cum = np.concatenate([[0], np.cumsum(mep_seg)])
        mep_total = mep_cum[-1]
        if mep_total > 1e-12:
            sample_s = np.linspace(0, mep_total, n_free_nodes + 2)[1:-1]
            mep_d1 = np.interp(sample_s, mep_cum, mep_path[:, 0])
            mep_d2 = np.interp(sample_s, mep_cum, mep_path[:, 1])
            mep_nodes = np.column_stack([mep_d1, mep_d2])
            mep_nodes[:, 0] = np.clip(mep_nodes[:, 0], d1_bounds[0], d1_bounds[1])
            mep_nodes[:, 1] = np.clip(mep_nodes[:, 1], d2_bounds[0], d2_bounds[1])
            initial_guesses.append(('mep', mep_nodes.flatten()))

    best_action = np.inf
    best_path = None
    best_label = None
    best_nodes = None

    for label, x0 in initial_guesses:
        try:
            result = optimize.minimize(
                _action_objective,
                x0,
                args=(start, end, spline, E_incident, mass, d1_bounds, d2_bounds),
                method='L-BFGS-B',
                bounds=bounds,
                options={'maxiter': 500, 'ftol': 1e-12}
            )

            if result.success or result.fun < best_action:
                path = _nodes_to_path(result.x, start, end, n_interp=200)
                action = compute_action(path, spline, E_incident, mass)

                if action < best_action:
                    best_action = action
                    best_path = path
                    best_label = label
                    best_nodes = result.x.reshape(-1, 2)
        except Exception:
            continue

    return best_path, best_action, best_label, best_nodes


def compute_path_curvature(path, canonical_pos, tautomeric_pos):
    """
    Compute a scalar curvature measure: the maximum perpendicular
    deviation of the path from the straight line connecting endpoints.
    Positive = toward high-d1/low-d2 corner; negative = opposite.
    """
    start = canonical_pos
    end = tautomeric_pos
    line_vec = end - start
    line_len = np.linalg.norm(line_vec)
    if line_len < 1e-10:
        return 0.0

    line_hat = line_vec / line_len
    perp_hat = np.array([-line_hat[1], line_hat[0]])

    max_dev = 0.0
    for p in path:
        delta = p - start
        perp_dist = np.dot(delta, perp_hat)
        if abs(perp_dist) > abs(max_dev):
            max_dev = perp_dist

    return max_dev


def get_path_barriers(path, spline, E_canonical, E_tautomeric):
    """
    Extract barrier heights from the energy profile along a given path.

    Returns:
        DV1_path: forward barrier (max energy along path - E_canonical)
        DV2_path: reverse barrier (max energy along path - E_tautomeric)
        E_max:    absolute energy at the path maximum
        max_idx:  index of the maximum along the path
    """
    energies = np.array([get_energy(spline, p[0], p[1]) for p in path])
    max_idx = np.argmax(energies)
    E_max = energies[max_idx]

    DV1_path = E_max - E_canonical
    DV2_path = E_max - E_tautomeric

    return DV1_path, DV2_path, E_max, max_idx


def find_map_self_consistent(spline, d1, d2, canonical_pos, tautomeric_pos,
                              E_canonical, E_tautomeric, mass,
                              n_free_nodes=24, scf_tol=1e-4,
                              scf_maxiter=10, label="forward",
                              mep_path=None):
    """
    Find the MAP path with a self-consistent barrier height.

    The MAP path depends on the incident energy used to seed the search,
    and the barrier height depends on the resulting path. This function
    iterates until the barrier used to set the test energy matches the
    barrier extracted from the converged path.

    For the forward direction, the barrier is referenced to E_canonical.
    For the reverse direction, the barrier is referenced to E_tautomeric.

    The initial guess for the barrier is obtained from a straight-line
    path between the two minima (no MEP dependence). The MEP geometry
    may be used as one of several initial guesses for the optimiser,
    but does not determine the barrier or constrain the result.

    Parameters:
        label: "forward" or "reverse" — determines which minimum is the
               reference for the barrier height
        mep_path: optional MEP path array to use as an additional
                  initial guess for the MAP optimiser

    Returns:
        best_path, best_nodes, DV, curvature, best_label, converged
    """
    if label == "forward":
        E_ref = E_canonical
    else:
        E_ref = E_tautomeric

    # --- Initial barrier guess from straight-line path (MEP-free) ---
    n_init = 200
    straight_path = np.array([
        canonical_pos + t * (tautomeric_pos - canonical_pos)
        for t in np.linspace(0, 1, n_init)
    ])
    straight_energies = np.array([
        get_energy(spline, p[0], p[1]) for p in straight_path
    ])
    DV_guess = np.max(straight_energies) - E_ref

    print(f"    SCF iteration 0: ΔV({label}) guess = {DV_guess:.4f} eV "
          f"(from straight-line path)")

    DV_current = DV_guess
    best_path = None
    best_nodes = None
    best_label_init = None
    converged = False
    delta = np.inf

    for scf_iter in range(1, scf_maxiter + 1):
        E_test = E_ref + DV_current * 0.5

        path, action, init_label, nodes = find_instanton_variational(
            spline, d1, d2, canonical_pos, tautomeric_pos,
            E_test, mass, n_free_nodes, mep_path=mep_path
        )

        if path is None:
            print(f"    SCF iteration {scf_iter}: MAP optimisation failed")
            break

        DV1_path, DV2_path, _, _ = get_path_barriers(
            path, spline, E_canonical, E_tautomeric
        )

        if label == "forward":
            DV_new = DV1_path
        else:
            DV_new = DV2_path

        delta = abs(DV_new - DV_current)
        print(f"    SCF iteration {scf_iter}: ΔV({label}) = {DV_new:.4f} eV "
              f"(Δ = {delta:.2e} eV, init: {init_label})")

        best_path = path
        best_nodes = nodes
        best_label_init = init_label
        DV_current = DV_new

        if delta < scf_tol:
            converged = True
            print(f"    SCF converged in {scf_iter} iterations")
            break

    if not converged:
        print(f"    SCF did not converge in {scf_maxiter} iterations "
              f"(final Δ = {delta:.2e} eV)")

    curvature = compute_path_curvature(best_path, canonical_pos, tautomeric_pos)

    return best_path, best_nodes, DV_current, curvature, best_label_init, converged


# ============================================================
# 5. WKB ACTION AND TRANSMISSION
# ============================================================
def compute_action(path_points, spline, E_incident, mass):
    """
    Compute the WKB action integral along a discretised path.

    The semiclassical (WKB) action for tunnelling through a barrier is:

        S = ∫ √(2m [V(s) − E] / ħ²) ds

    integrated only over the classically forbidden region where
    V(s) > E.  The integral is evaluated by the midpoint rule on
    consecutive path segments.

    Parameters
    ----------
    path_points : ndarray, shape (N, 2)
        Dense path in (d₁, d₂) space.
    spline : RectBivariateSpline
        Interpolated PES.
    E_incident : float
        Incident energy (eV), i.e. the energy of the tunnelling
        particle.  Segments where V < E_incident (classically allowed)
        contribute zero action.
    mass : float
        Effective tunnelling mass in eV·s²/Å².

    Returns
    -------
    float
        Dimensionless action (the exponent in T ≈ exp(−2S)).
    """
    action = 0.0
    for i in range(len(path_points) - 1):
        p1 = path_points[i]
        p2 = path_points[i + 1]
        mid = 0.5 * (p1 + p2)

        V = get_energy(spline, mid[0], mid[1])
        diff = V - E_incident

        if diff > 0:
            ds = np.sqrt((p2[0] - p1[0])**2 + (p2[1] - p1[1])**2)
            action += np.sqrt((2 * mass) / HBAR**2 * diff) * ds

    return action


def wkb_transmission_along_path(E, path, spline, mass):
    """
    WKB tunnelling transmission coefficient T(E) along a fixed path.

    T(E) = exp(−2S), where S is the action integral.  The result is
    clipped to [10⁻³⁰⁰, 1] to avoid numerical underflow/overflow.

    Parameters
    ----------
    E : float
        Incident energy (eV).
    path : ndarray, shape (N, 2)
        Fixed tunnelling path.
    spline : RectBivariateSpline
        Interpolated PES.
    mass : float
        Tunnelling mass (eV·s²/Å²).

    Returns
    -------
    float
        Transmission coefficient in [0, 1].
    """
    action = compute_action(path, spline, E, mass)
    return float(np.clip(np.exp(-2 * action), 1e-300, 1.0))


# ============================================================
# 6. KAPPA(T) INTEGRATION
# ============================================================
def wkb_kappa_2d(T_K, spline, d1, d2, mass, DV, E_ref, path,
                  n_energies=500):
    """
    Compute the tunnelling correction factor κ(T) along a fixed path.

    κ is the ratio of the quantum-mechanical to classical rate through
    the barrier.  It is computed by numerically integrating:

        κ(T) = β · exp(β·ΔV) · ∫₀^∞ T(E) · exp(−βE) dE

    where β = 1/(k_B T), ΔV is the classical barrier height, and T(E)
    is the WKB transmission probability evaluated along ``path``.

    The integration grid extends from near-zero to 2.5×ΔV, which is
    wide enough to capture the Boltzmann-weighted tail.  κ is floored
    at 1.0 (the classical limit — tunnelling can only enhance the rate).

    Parameters
    ----------
    T_K : float
        Temperature (K).
    spline : RectBivariateSpline
        Interpolated PES.
    d1, d2 : ndarray
        Coordinate arrays (passed through but unused here; kept for
        interface consistency).
    mass : float
        Tunnelling mass (eV·s²/Å²).
    DV : float
        Barrier height relative to ``E_ref`` (eV).
    E_ref : float
        Absolute energy of the reference minimum (eV).
    path : ndarray, shape (N, 2)
        Fixed tunnelling path.
    n_energies : int
        Number of quadrature points for the energy integral.

    Returns
    -------
    kappa : float
        Tunnelling correction factor (≥ 1.0).
    E_grid : ndarray
        Energy grid used for integration (eV, relative to E_ref).
    T_values : ndarray
        T(E) at each grid point.
    """
    beta = 1.0 / (KB * T_K)
    E_grid = np.linspace(1e-6, DV * 2.5, n_energies)

    T_values = np.zeros(n_energies)
    for i, E in enumerate(E_grid):
        T_values[i] = wkb_transmission_along_path(E + E_ref, path, spline, mass)

    integrand = T_values * np.exp(-beta * E_grid)
    kappa = beta * np.exp(beta * DV) * np.trapz(integrand, E_grid)

    return max(kappa, 1.0), E_grid, T_values


# --- Parallel worker for MAP kappa ---
def _instanton_worker(args_tuple):
    """
    Multiprocessing worker: optimise the MAP path at a single incident energy.

    Receives all data as plain arrays (picklable), rebuilds the spline
    locally, runs the MAP optimiser, and returns the transmission
    coefficient T(E) = exp(−2S).
    """
    (E_abs, d1, d2, energies_smooth, canonical_pos, tautomeric_pos,
     mass, n_free_nodes, mep_path) = args_tuple

    spline = _rebuild_spline(d1, d2, energies_smooth)

    best_path, best_action, _, _ = find_instanton_variational(
        spline, d1, d2, canonical_pos, tautomeric_pos,
        E_abs, mass, n_free_nodes, mep_path=mep_path
    )

    if best_path is not None:
        T_val = float(np.clip(np.exp(-2 * best_action), 1e-300, 1.0))
    else:
        T_val = 0.0

    return T_val


def wkb_kappa_2d_instanton(T_K, spline, d1, d2, mass, DV, E_ref,
                            canonical_pos, tautomeric_pos,
                            n_free_nodes=24, n_energies=300,
                            n_workers=1, energies_smooth=None,
                            mep_path=None):
    """
    Compute κ(T) with per-energy MAP path optimisation.

    Unlike ``wkb_kappa_2d``, which evaluates T(E) along a single
    pre-computed path, this function re-optimises the MAP at every
    incident energy in the integration grid.  This is the most rigorous
    treatment — the optimal tunnelling path depends on energy because
    the classically forbidden region changes shape — but it is far more
    expensive.

    Parallelism is supported: if ``n_workers > 1`` and
    ``energies_smooth`` is provided (so the spline can be rebuilt in
    each worker), the energy loop is distributed across a
    ``multiprocessing.Pool``.

    Parameters
    ----------
    T_K : float
        Temperature (K).
    spline : RectBivariateSpline
        Interpolated PES (used in serial mode).
    d1, d2 : ndarray
        Coordinate arrays.
    mass : float
        Tunnelling mass (eV·s²/Å²).
    DV : float
        Barrier height relative to E_ref (eV).
    E_ref : float
        Absolute energy of the reference minimum (eV).
    canonical_pos, tautomeric_pos : ndarray
        Path endpoints.
    n_free_nodes : int
        Number of free interior nodes in the MAP discretisation.
    n_energies : int
        Number of energy quadrature points.
    n_workers : int
        Number of parallel processes (1 = serial).
    energies_smooth : ndarray or None
        Smoothed energy surface (needed for parallel mode to rebuild
        the spline in each worker).
    mep_path : ndarray or None
        MEP path to use as an additional MAP seed.

    Returns
    -------
    kappa : float
        Tunnelling correction factor (≥ 1.0).
    E_grid : ndarray
        Energy integration grid (eV, relative to E_ref).
    T_values : ndarray
        T(E) at each grid point.
    """
    beta = 1.0 / (KB * T_K)
    E_grid = np.linspace(1e-6, DV * 2.5, n_energies)

    if n_workers > 1 and energies_smooth is not None:
        # --- Parallel execution ---
        worker_args = [
            (E + E_ref, d1, d2, energies_smooth,
             canonical_pos, tautomeric_pos, mass, n_free_nodes, mep_path)
            for E in E_grid
        ]

        print(f"    Dispatching {n_energies} energy points "
              f"across {n_workers} workers...")

        with mp.Pool(processes=n_workers) as pool:
            T_values = np.array(pool.map(_instanton_worker, worker_args))

        print(f"    All {n_energies} energy points complete.")

    else:
        # --- Serial execution ---
        T_values = np.zeros(n_energies)

        for i, E in enumerate(E_grid):
            best_path, best_action, _, _ = find_instanton_variational(
                spline, d1, d2, canonical_pos, tautomeric_pos,
                E + E_ref, mass, n_free_nodes, mep_path=mep_path
            )
            if best_path is not None:
                T_values[i] = float(np.clip(
                    np.exp(-2 * best_action), 1e-300, 1.0))

            if (i + 1) % 50 == 0:
                print(f"    MAP kappa: {i+1}/{n_energies} energies done...")

    integrand = T_values * np.exp(-beta * E_grid)
    kappa = beta * np.exp(beta * DV) * np.trapz(integrand, E_grid)

    return max(kappa, 1.0), E_grid, T_values


# --- Parallel worker for temperature sweep ---
def _temp_worker(args_tuple):
    """
    Multiprocessing worker for the temperature sweep.

    Computes all four κ values (MEP forward/reverse, MAP forward/reverse)
    and the corresponding Eyring rate constants at a single temperature.
    Returns an 8-tuple that is unpacked by the caller.
    """
    (T, d1, d2, energies_smooth, mass,
     mep_final_DV1, mep_final_DV2, E_canonical, E_tautomeric,
     mep_path, inst_path_f, inst_path_r,
     inst_DV1, inst_DV2) = args_tuple

    spline = _rebuild_spline(d1, d2, energies_smooth)

    # MEP forward κ
    kap_mep_f, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                    mep_final_DV1, E_canonical,
                                    mep_path, n_energies=300)
    # MEP reverse κ
    kap_mep_r, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                    mep_final_DV2, E_tautomeric,
                                    mep_path, n_energies=300)

    kf_mep = eyring_rate(kap_mep_f, T, mep_final_DV1)
    kr_mep = eyring_rate(kap_mep_r, T, mep_final_DV2)

    # MAP forward κ
    kap_if, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                 inst_DV1, E_canonical,
                                 inst_path_f, n_energies=300)
    kf_inst = eyring_rate(kap_if, T, inst_DV1)

    # MAP reverse κ
    kap_ir, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                 inst_DV2, E_tautomeric,
                                 inst_path_r, n_energies=300)
    kr_inst = eyring_rate(kap_ir, T, inst_DV2)

    return (kap_mep_f, kap_mep_r, kf_mep, kr_mep,
            kap_if, kap_ir, kf_inst, kr_inst)


# ============================================================
# 7. EYRING RATE CONSTANTS
# ============================================================
def eyring_rate(kappa, T_K, delta_E_eV):
    """
    Compute the tunnelling-corrected Eyring (transition-state theory) rate.

    The Eyring equation gives the unimolecular rate constant:

        k = κ · (k_B T / h) · exp(−ΔE‡ / k_B T)

    where κ is the tunnelling correction factor, ΔE‡ is the electronic
    barrier height (no zero-point or thermal corrections), and the
    prefactor k_B T / h is the universal frequency factor from TST.

    Parameters
    ----------
    kappa : float
        Tunnelling correction factor (≥ 1).
    T_K : float
        Temperature (K).
    delta_E_eV : float
        Electronic barrier height (eV).

    Returns
    -------
    float
        Rate constant (s⁻¹).
    """
    prefactor = (KB_J * T_K) / H_J
    delta_E_J_mol = delta_E_eV * EV_TO_J_MOL
    boltzmann = np.exp(-delta_E_J_mol / (R_J * T_K))
    return kappa * prefactor * boltzmann


# ============================================================
# 8. MAIN
# ============================================================
def main():
    """
    Entry point: orchestrate the full 2D WKB tunnelling analysis.

    Execution flow:
      1. Parse CLI arguments and set up physical parameters.
      2. Load the 2D PES and build the spline interpolant.
      3. Locate canonical and tautomeric minima.
      4. Estimate the saddle point.
      5. Compute the MEP via the string method.
      6. Compute forward and reverse MAP paths (self-consistent).
      7. Evaluate κ(T) for MEP and MAP at the reporting temperature.
      8. Compute Eyring rate constants.
      9. Generate diagnostic plots (paths, transmission, action, Arrhenius).
     10. Write a CSV of rates vs. temperature and print a summary.
    """
    args = parse_args()
    grid_dir = args.grid_dir
    T_REPORT = args.T_REPORT
    mass = M_PROTON * args.mass_factor
    n_inst_nodes = args.n_inst_nodes
    n_workers = args.n_workers

    print("=" * 60)
    print("  2D WKB Tunnelling Correction Calculator")
    print("  (MEP AND MAP)")
    print("=" * 60)
    if n_workers > 1:
        print(f"  Parallelisation: {n_workers} workers")

    # --------------------------------------------------------
    # Load PES
    # --------------------------------------------------------
    print(f"\nLoading 2D PES from {grid_dir}/...")
    d1, d2, energies_raw, energies_smooth, spline = load_pes(grid_dir, args.smooth)
    print(f"  Grid: {len(d1)} x {len(d2)} = {len(d1)*len(d2)} points")
    print(f"  d1 range: {d1[0]:.3f} – {d1[-1]:.3f} Å")
    print(f"  d2 range: {d2[0]:.3f} – {d2[-1]:.3f} Å")
    print(f"  Raw energy range: {np.min(energies_raw):.4f} – {np.max(energies_raw):.4f} eV")

    # --------------------------------------------------------
    # Find true minima
    # --------------------------------------------------------
    # Initial guesses for the minima: canonical is near the short-distance
    # corner (small d₁, small d₂); tautomeric is near the long-distance corner.
    print("\nFinding canonical minimum...")
    canon_guess = [d1[0] + 0.1, d2[0] + 0.1]
    canonical_pos, E_canonical = find_minimum(spline, d1, d2, canon_guess)
    print(f"  Canonical minimum at d1 = {canonical_pos[0]:.4f}, d2 = {canonical_pos[1]:.4f} Å")
    print(f"  E(canonical) = {E_canonical:.4f} eV")

    print("\nFinding tautomeric minimum...")
    taut_guess = [d1[-1] - 0.1, d2[-1] - 0.1]
    tautomeric_pos, E_tautomeric = find_minimum(spline, d1, d2, taut_guess)
    print(f"  Tautomeric minimum at d1 = {tautomeric_pos[0]:.4f}, d2 = {tautomeric_pos[1]:.4f} Å")
    print(f"  E(tautomeric) = {E_tautomeric:.4f} eV")

    E_ref = E_canonical
    DE_taut = E_tautomeric - E_ref
    print(f"\n  Tautomeric energy (relative) = {DE_taut:.4f} eV")

    # --------------------------------------------------------
    # Find saddle point
    # --------------------------------------------------------
    print("\nSearching for saddle point...")
    saddle_pos, E_saddle = find_saddle_point(spline, d1, d2, canonical_pos, tautomeric_pos)
    DV1 = E_saddle - E_ref
    DV2 = E_saddle - E_tautomeric
    DE = E_tautomeric - E_ref

    print(f"  Saddle point at d1 = {saddle_pos[0]:.4f}, d2 = {saddle_pos[1]:.4f} Å")
    print(f"  E(saddle) = {E_saddle:.4f} eV")
    print(f"\n  Forward barrier  ΔV₁ = {DV1:.4f} eV")
    print(f"  Reverse barrier  ΔV₂ = {DV2:.4f} eV")
    print(f"  Asymmetry        ΔE  = {DE:.4f} eV")

    # --------------------------------------------------------
    # Find MEP
    # --------------------------------------------------------
    print("\nFinding minimum energy path (MEP)...")
    mep_path, mep_energies, mep_arc = find_mep(spline, d1, d2,
                                                 canonical_pos, tautomeric_pos,
                                                 n_images=100)
    mep_energies_rel = mep_energies - E_ref
    mep_DV1 = np.max(mep_energies_rel)
    mep_DV2 = np.max(mep_energies_rel) - mep_energies_rel[-1]
    ts_idx = np.argmax(mep_energies_rel)

    print(f"  MEP forward barrier  = {mep_DV1:.4f} eV")
    print(f"  MEP reverse barrier  = {mep_DV2:.4f} eV")
    print(f"  MEP arc length       = {mep_arc[-1]:.4f} Å")
    print(f"  TS on MEP at d1 = {mep_path[ts_idx, 0]:.3f}, d2 = {mep_path[ts_idx, 1]:.3f} Å")

    # Use whichever barrier is higher: the saddle-point estimate or the
    # MEP maximum.  In practice these should be very similar; this guard
    # handles cases where the string method undershoots the true TS.
    if DV1 > mep_DV1:
        print(f"\n  MEP: using saddle-point barrier: {DV1:.4f} eV")
        mep_final_DV1 = DV1
        mep_final_DV2 = DV2
    else:
        print(f"\n  MEP: using MEP barrier: {mep_DV1:.4f} eV")
        mep_final_DV1 = mep_DV1
        mep_final_DV2 = mep_DV2

    # --------------------------------------------------------
    # Plot MEP on 2D surface
    # Good for comparing to 1D ML-NEB data
    # --------------------------------------------------------
    D1, D2 = np.meshgrid(d1, d2, indexing='ij')
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    ax = axes[0]
    levels = np.linspace(0, min(np.max(energies_raw), 2.0), 30)
    contour = ax.contourf(D1, D2, energies_raw, levels=levels, cmap='viridis')
    ax.contour(D1, D2, energies_raw, levels=levels, colors='black',
               linewidths=0.3, alpha=0.5)
    ax.plot(mep_path[:, 0], mep_path[:, 1], 'r-', lw=2, label='MEP')
    ax.plot(saddle_pos[0], saddle_pos[1], 'y*', markersize=15, label='Saddle point')
    ax.plot(canonical_pos[0], canonical_pos[1], 'w*', markersize=12, label='Canonical')
    ax.plot(tautomeric_pos[0], tautomeric_pos[1], 'r^', markersize=10, label='Tautomeric')
    plt.colorbar(contour, ax=ax, label='Energy (eV)')
    ax.set_xlabel(r'$d_1$ (Å)')
    ax.set_ylabel(r'$d_2$ (Å)')
    ax.set_title('2D PES with MEP')
    ax.legend(fontsize=8)

    ax = axes[1]
    ax.plot(mep_arc, mep_energies_rel, 'b-', lw=2)
    ax.axhline(0, color='gray', lw=0.8, ls='--')
    ax.axhline(mep_final_DV1, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₁ = {mep_final_DV1:.3f} eV')
    ax.set_xlabel('Path Length MEP (Å)')
    ax.set_ylabel('Energy (eV)')
    ax.set_title('Energy profile along 2D MEP')
    ax.legend(fontsize=9)

    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_mep_analysis.png', dpi=150)
    plt.close()
    print(f"\nSaved: {grid_dir}/2d_mep_analysis.png")

    # --------------------------------------------------------
    # Find MAP — forward (self-consistent, MEP-free)
    # --------------------------------------------------------
    print(f"\nSearching for forward MAP ({n_inst_nodes} free nodes)...")
    (inst_path_f, inst_nodes_f, inst_DV1, inst_curv_f,
     inst_label_f, inst_conv_f) = find_map_self_consistent(
        spline, d1, d2, canonical_pos, tautomeric_pos,
        E_canonical, E_tautomeric, mass,
        n_free_nodes=n_inst_nodes,
        scf_tol=args.map_scf_tol,
        scf_maxiter=args.map_scf_maxiter,
        label="forward",
        mep_path=mep_path
    )
    inst_DV1_check, inst_DV2_from_fwd, _, _ = get_path_barriers(
        inst_path_f, spline, E_canonical, E_tautomeric
    )

    print(f"  Forward MAP:")
    print(f"    ΔV₁(MAP_f) = {inst_DV1:.4f} eV")
    print(f"    ΔV₂ seen by forward path = {inst_DV2_from_fwd:.4f} eV")
    print(f"    Path curvature: {inst_curv_f:.4f} Å")
    print(f"    Best initialisation: {inst_label_f}")

    # --------------------------------------------------------
    # Find MAP — reverse (self-consistent, MEP-free)
    # --------------------------------------------------------
    print(f"\nSearching for reverse MAP ({n_inst_nodes} free nodes)...")
    (inst_path_r, inst_nodes_r, inst_DV2, inst_curv_r,
     inst_label_r, inst_conv_r) = find_map_self_consistent(
        spline, d1, d2, canonical_pos, tautomeric_pos,
        E_canonical, E_tautomeric, mass,
        n_free_nodes=n_inst_nodes,
        scf_tol=args.map_scf_tol,
        scf_maxiter=args.map_scf_maxiter,
        label="reverse",
        mep_path=mep_path
    )
    inst_DV1_from_rev, inst_DV2_check, _, _ = get_path_barriers(
        inst_path_r, spline, E_canonical, E_tautomeric
    )

    print(f"  Reverse MAP:")
    print(f"    ΔV₂(MAP_r) = {inst_DV2:.4f} eV")
    print(f"    ΔV₁ seen by reverse path = {inst_DV1_from_rev:.4f} eV")
    print(f"    Path curvature: {inst_curv_r:.4f} Å")
    print(f"    Best initialisation: {inst_label_r}")

    # --------------------------------------------------------
    # Report path differences
    # --------------------------------------------------------
    path_diff = np.mean(np.sqrt(np.sum((inst_path_f - inst_path_r)**2, axis=1)))
    print(f"\n  Mean path separation (MAP_f vs MAP_r): {path_diff:.4f} Å")
    if path_diff < 0.001:
        print(f"  -> Forward and reverse MAP paths are essentially identical")
    else:
        print(f"  -> Forward and reverse MAP paths differ")

    # --------------------------------------------------------
    # WKB κ using MEP — forward and reverse independently
    # --------------------------------------------------------
    print(f"\nComputing WKB κ (MEP, forward) at T = {T_REPORT:.1f} K...")
    kappa_mep_f, E_grid_mep_f, T_mep_f = wkb_kappa_2d(
        T_REPORT, spline, d1, d2, mass, mep_final_DV1,
        E_canonical, mep_path
    )
    print(f"  κ_MEP(forward) = {kappa_mep_f:.4f}")

    print(f"\nComputing WKB κ (MEP, reverse) at T = {T_REPORT:.1f} K...")
    kappa_mep_r, E_grid_mep_r, T_mep_r = wkb_kappa_2d(
        T_REPORT, spline, d1, d2, mass, mep_final_DV2,
        E_tautomeric, mep_path
    )
    print(f"  κ_MEP(reverse) = {kappa_mep_r:.4f}")

    # --------------------------------------------------------
    # WKB κ using MAP — forward (own path, own barrier)
    # --------------------------------------------------------
    print(f"\nComputing WKB κ_f (MAP forward) at T = {T_REPORT:.1f} K...")
    kappa_inst_f, E_grid_inst_f, T_inst_f = wkb_kappa_2d_instanton(
        T_REPORT, spline, d1, d2, mass, inst_DV1, E_canonical,
        canonical_pos, tautomeric_pos, n_inst_nodes,
        n_workers=n_workers, energies_smooth=energies_smooth,
        mep_path=mep_path
    )
    print(f"  κ_MAP(forward) = {kappa_inst_f:.4f}")

    # --------------------------------------------------------
    # WKB κ using MAP — reverse (own path, own barrier)
    # --------------------------------------------------------
    print(f"\nComputing WKB κ_r (MAP reverse) at T = {T_REPORT:.1f} K...")
    kappa_inst_r, E_grid_inst_r, T_inst_r = wkb_kappa_2d_instanton(
        T_REPORT, spline, d1, d2, mass, inst_DV2, E_tautomeric,
        canonical_pos, tautomeric_pos, n_inst_nodes,
        n_workers=n_workers, energies_smooth=energies_smooth,
        mep_path=mep_path
    )
    print(f"  κ_MAP(reverse) = {kappa_inst_r:.4f}")

    # --------------------------------------------------------
    # Eyring rates
    # --------------------------------------------------------
    # MEP: direction-specific κ, MEP barriers
    k_f_mep = eyring_rate(kappa_mep_f, T_REPORT, mep_final_DV1)
    k_r_mep = eyring_rate(kappa_mep_r, T_REPORT, mep_final_DV2)

    # MAP: direction-specific κ, direction-specific barriers
    k_f_inst = eyring_rate(kappa_inst_f, T_REPORT, inst_DV1)
    k_r_inst = eyring_rate(kappa_inst_r, T_REPORT, inst_DV2)

    print(f"\n{'='*60}")
    print(f"  Results at T = {T_REPORT:.2f} K")
    print(f"{'='*60}")
    print(f"\n  [MEP]  (barriers: ΔV₁ = {mep_final_DV1:.4f}, ΔV₂ = {mep_final_DV2:.4f} eV)")
    print(f"    κ_f       = {kappa_mep_f:.4f}")
    print(f"    κ_r       = {kappa_mep_r:.4f}")
    print(f"    k_f       = {k_f_mep:.4e} s⁻¹")
    print(f"    k_r       = {k_r_mep:.4e} s⁻¹")
    print(f"    τ_f       = {1/k_f_mep:.4e} s")
    print(f"    τ_r       = {1/k_r_mep:.4e} s")
    print(f"\n  [MAP forward]  (barrier: ΔV₁ = {inst_DV1:.4f} eV)")
    print(f"    κ_f       = {kappa_inst_f:.4f}")
    print(f"    k_f       = {k_f_inst:.4e} s⁻¹")
    print(f"    τ_f       = {1/k_f_inst:.4e} s")
    print(f"\n  [MAP reverse]  (barrier: ΔV₂ = {inst_DV2:.4f} eV)")
    print(f"    κ_r       = {kappa_inst_r:.4f}")
    print(f"    k_r       = {k_r_inst:.4e} s⁻¹")
    print(f"    τ_r       = {1/k_r_inst:.4e} s")

    # --------------------------------------------------------
    # Transmission plots — Forward and Reverse
    # --------------------------------------------------------
    beta_plot = 1.0 / (KB * T_REPORT)

    # (1) Forward: MEP vs MAP
    T_boltz_mep_f = T_mep_f * np.exp(-beta_plot * E_grid_mep_f)
    T_boltz_inst_f = T_inst_f * np.exp(-beta_plot * E_grid_inst_f)

    fig, ax = plt.subplots(figsize=(7, 5))
    ax2 = ax.twinx()
    l1, = ax.semilogy(E_grid_mep_f, T_mep_f, color='#c85000', lw=2,
                      label='T(E) — MEP')
    l2, = ax.semilogy(E_grid_inst_f, T_inst_f, color='#0055c8', lw=2,
                      ls='--', label='T(E) — MAP')
    l3, = ax2.semilogy(E_grid_mep_f, T_boltz_mep_f, color='#c85000',
                       lw=1.5, ls=':', alpha=0.7,
                       label='T(E)·exp(−βE) — MEP')
    l4, = ax2.semilogy(E_grid_inst_f, T_boltz_inst_f, color='#0055c8',
                       lw=1.5, ls=':', alpha=0.7,
                       label='T(E)·exp(−βE) — MAP')
    ax.axvline(mep_final_DV1, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₁(MEP) = {mep_final_DV1:.3f} eV')
    ax.axvline(inst_DV1, color='#0055c8', lw=0.8, ls=':',
               label=f'ΔV₁(MAP) = {inst_DV1:.3f} eV')
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel('Tunnelling probability T(E)')
    ax2.set_ylabel('Tunnelling factor T(E)·exp(−βE)')
    ax.set_title(f'Forward tunnelling: MEP vs MAP — T = {T_REPORT:.1f} K')
    ax.legend([l1, l2, l3, l4],
              [l1.get_label(), l2.get_label(), l3.get_label(), l4.get_label()],
              fontsize=8, loc='center left')
    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_WKB_Tunnelling_forward.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_WKB_Tunnelling_forward.png")

    # (2) Reverse: MEP vs MAP
    T_boltz_mep_r = T_mep_r * np.exp(-beta_plot * E_grid_mep_r)
    T_boltz_inst_r = T_inst_r * np.exp(-beta_plot * E_grid_inst_r)

    fig, ax = plt.subplots(figsize=(7, 5))
    ax2 = ax.twinx()
    l1, = ax.semilogy(E_grid_mep_r, T_mep_r, color='#c85000', lw=2,
                      label='T(E) — MEP')
    l2, = ax.semilogy(E_grid_inst_r, T_inst_r, color='#2ca02c', lw=2,
                      ls='--', label='T(E) — MAP')
    l3, = ax2.semilogy(E_grid_mep_r, T_boltz_mep_r, color='#c85000',
                       lw=1.5, ls=':', alpha=0.7,
                       label='T(E)·exp(−βE) — MEP')
    l4, = ax2.semilogy(E_grid_inst_r, T_boltz_inst_r, color='#2ca02c',
                       lw=1.5, ls=':', alpha=0.7,
                       label='T(E)·exp(−βE) — MAP')
    ax.axvline(mep_final_DV2, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₂(MEP) = {mep_final_DV2:.3f} eV')
    ax.axvline(inst_DV2, color='#2ca02c', lw=0.8, ls=':',
               label=f'ΔV₂(MAP) = {inst_DV2:.3f} eV')
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel('Tunnelling probability T(E)')
    ax2.set_ylabel('Tunnelling factor T(E)·exp(−βE)')
    ax.set_title(f'Reverse tunnelling: MEP vs MAP — T = {T_REPORT:.1f} K')
    ax.legend([l1, l2, l3, l4],
              [l1.get_label(), l2.get_label(), l3.get_label(), l4.get_label()],
              fontsize=8, loc='center left')
    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_WKB_Tunnelling_reverse.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_WKB_Tunnelling_reverse.png")

    # --------------------------------------------------------
    # Action difference: ΔS(E) = S_MEP(E) - S_MAP(E)
    # Positive ΔS means the MAP has lower action (higher
    # transmission) at that energy — this is the regime where
    # corner-cutting matters.
    # --------------------------------------------------------
    print("\nComputing action difference ΔS(E) = S_MEP - S_MAP...")
    n_action_pts = 200

    # --- Forward action comparison ---
    E_action_grid_f = np.linspace(1e-6, max(mep_final_DV1, inst_DV1) * 1.2,
                                  n_action_pts)
    S_mep_f_arr = np.zeros(n_action_pts)
    S_inst_f_arr = np.zeros(n_action_pts)
    for i, E in enumerate(E_action_grid_f):
        S_mep_f_arr[i] = compute_action(mep_path, spline, E + E_canonical, mass)
        S_inst_f_arr[i] = compute_action(inst_path_f, spline, E + E_canonical, mass)
    delta_S_f = S_mep_f_arr - S_inst_f_arr

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    ax = axes[0]
    ax.plot(E_action_grid_f, S_mep_f_arr, color='#c85000', lw=2,
            label=r'$S_{\mathrm{MEP}}(E)$')
    ax.plot(E_action_grid_f, S_inst_f_arr, color='#0055c8', lw=2, ls='--',
            label=r'$S_{\mathrm{MAP}}(E)$')
    ax.axvline(mep_final_DV1, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₁(MEP) = {mep_final_DV1:.3f} eV')
    ax.axvline(inst_DV1, color='#0055c8', lw=0.8, ls=':',
               label=f'ΔV₁(MAP) = {inst_DV1:.3f} eV')
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel('WKB action S(E)')
    ax.set_title('Forward: WKB action along MEP and MAP')
    ax.legend(fontsize=9)

    ax = axes[1]
    ax.plot(E_action_grid_f, delta_S_f, color='#0055c8', lw=2)
    ax.axhline(0, color='gray', lw=0.5, ls='-')
    ax.axvline(mep_final_DV1, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₁(MEP) = {mep_final_DV1:.3f} eV')
    ax.axvline(inst_DV1, color='#0055c8', lw=0.8, ls=':',
               label=f'ΔV₁(MAP) = {inst_DV1:.3f} eV')
    ax.fill_between(E_action_grid_f, 0, delta_S_f,
                    where=(delta_S_f > 0), alpha=0.3, color='#0055c8',
                    label='MAP favoured')
    ax.fill_between(E_action_grid_f, 0, delta_S_f,
                    where=(delta_S_f < 0), alpha=0.3, color='#c85000',
                    label='MEP favoured')
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel(r'$\Delta S(E) = S_{\mathrm{MEP}} - S_{\mathrm{MAP}}$')
    ax.set_title('Forward: action advantage of MAP over MEP')
    ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_action_difference_fwd.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_action_difference_fwd.png")

    # --- Reverse action comparison ---
    E_action_grid_r = np.linspace(1e-6, max(mep_final_DV2, inst_DV2) * 1.2,
                                  n_action_pts)
    S_mep_r_arr = np.zeros(n_action_pts)
    S_inst_r_arr = np.zeros(n_action_pts)
    for i, E in enumerate(E_action_grid_r):
        S_mep_r_arr[i] = compute_action(mep_path, spline, E + E_tautomeric, mass)
        S_inst_r_arr[i] = compute_action(inst_path_r, spline, E + E_tautomeric, mass)
    delta_S_r = S_mep_r_arr - S_inst_r_arr

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    ax = axes[0]
    ax.plot(E_action_grid_r, S_mep_r_arr, color='#c85000', lw=2,
            label=r'$S_{\mathrm{MEP}}(E)$')
    ax.plot(E_action_grid_r, S_inst_r_arr, color='#2ca02c', lw=2, ls='--',
            label=r'$S_{\mathrm{MAP}}(E)$')
    ax.axvline(mep_final_DV2, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₂(MEP) = {mep_final_DV2:.3f} eV')
    ax.axvline(inst_DV2, color='#2ca02c', lw=0.8, ls=':',
               label=f'ΔV₂(MAP) = {inst_DV2:.3f} eV')
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel('WKB action S(E)')
    ax.set_title('Reverse: WKB action along MEP and MAP')
    ax.legend(fontsize=9)

    ax = axes[1]
    ax.plot(E_action_grid_r, delta_S_r, color='#2ca02c', lw=2)
    ax.axhline(0, color='gray', lw=0.5, ls='-')
    ax.axvline(mep_final_DV2, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₂(MEP) = {mep_final_DV2:.3f} eV')
    ax.axvline(inst_DV2, color='#2ca02c', lw=0.8, ls=':',
               label=f'ΔV₂(MAP) = {inst_DV2:.3f} eV')
    ax.fill_between(E_action_grid_r, 0, delta_S_r,
                    where=(delta_S_r > 0), alpha=0.3, color='#2ca02c',
                    label='MAP favoured')
    ax.fill_between(E_action_grid_r, 0, delta_S_r,
                    where=(delta_S_r < 0), alpha=0.3, color='#c85000',
                    label='MEP favoured')
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel(r'$\Delta S(E) = S_{\mathrm{MEP}} - S_{\mathrm{MAP}}$')
    ax.set_title('Reverse: action advantage of MAP over MEP')
    ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_action_difference_rev.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_action_difference_rev.png")

    # --------------------------------------------------------
    # Temperature dependence — MEP and MAP (independent paths)
    # --------------------------------------------------------
    print(f"\nCalculating rates over {T_RANGE[0]}–{T_RANGE[1]} K...")
    T_arr = np.linspace(T_RANGE[0], T_RANGE[1], N_TEMPS)

    if n_workers > 1:
        # --- Parallel temperature sweep ---
        print(f"  Dispatching {N_TEMPS} temperatures "
              f"across {n_workers} workers...")

        worker_args = [
            (T, d1, d2, energies_smooth, mass,
             mep_final_DV1, mep_final_DV2, E_canonical, E_tautomeric,
             mep_path, inst_path_f, inst_path_r,
             inst_DV1, inst_DV2)
            for T in T_arr
        ]

        with mp.Pool(processes=n_workers) as pool:
            results = pool.map(_temp_worker, worker_args)

        kap_mep_f_arr = np.array([r[0] for r in results])
        kap_mep_r_arr = np.array([r[1] for r in results])
        kf_mep_arr = np.array([r[2] for r in results])
        kr_mep_arr = np.array([r[3] for r in results])
        kap_inst_f_arr = np.array([r[4] for r in results])
        kap_inst_r_arr = np.array([r[5] for r in results])
        kf_inst_arr = np.array([r[6] for r in results])
        kr_inst_arr = np.array([r[7] for r in results])

        print(f"  All {N_TEMPS} temperatures complete.")

    else:
        # --- Serial temperature sweep ---
        kf_mep_arr = np.zeros(N_TEMPS)
        kr_mep_arr = np.zeros(N_TEMPS)
        kap_mep_f_arr = np.zeros(N_TEMPS)
        kap_mep_r_arr = np.zeros(N_TEMPS)
        kf_inst_arr = np.zeros(N_TEMPS)
        kr_inst_arr = np.zeros(N_TEMPS)
        kap_inst_f_arr = np.zeros(N_TEMPS)
        kap_inst_r_arr = np.zeros(N_TEMPS)

        for i, T in enumerate(T_arr):
            # MEP forward κ
            kap_mf, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                         mep_final_DV1, E_canonical,
                                         mep_path, n_energies=300)
            # MEP reverse κ
            kap_mr, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                         mep_final_DV2, E_tautomeric,
                                         mep_path, n_energies=300)
            kap_mep_f_arr[i] = kap_mf
            kap_mep_r_arr[i] = kap_mr
            kf_mep_arr[i] = eyring_rate(kap_mf, T, mep_final_DV1)
            kr_mep_arr[i] = eyring_rate(kap_mr, T, mep_final_DV2)

            # MAP forward
            kap_if, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                         inst_DV1, E_canonical,
                                         inst_path_f, n_energies=300)
            kap_inst_f_arr[i] = kap_if
            kf_inst_arr[i] = eyring_rate(kap_if, T, inst_DV1)

            # MAP reverse
            kap_ir, _, _ = wkb_kappa_2d(T, spline, d1, d2, mass,
                                         inst_DV2, E_tautomeric,
                                         inst_path_r, n_energies=300)
            kap_inst_r_arr[i] = kap_ir
            kr_inst_arr[i] = eyring_rate(kap_ir, T, inst_DV2)

            if (i + 1) % 20 == 0:
                print(f"  {i+1}/{N_TEMPS} temperatures done...")

    # Arrhenius plots — Forward and Reverse
    inv_T = 1000.0 / T_arr

    # (1) Forward: MEP vs MAP
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.semilogy(inv_T, kf_mep_arr, color='#c85000', lw=2,
                label=r'$k_f$ MEP')
    ax.semilogy(inv_T, kf_inst_arr, color='#0055c8', lw=2, ls='--',
                label=r'$k_f$ MAP')
    ax.axvline(1000.0 / T_REPORT, color='gray', lw=0.8, ls=':',
               label=f'T = {T_REPORT:.0f} K')
    ax.set_xlabel('1000 / T  (K⁻¹)')
    ax.set_ylabel('Rate constant  (s⁻¹)')
    ax.set_title('Forward Eyring rates: MEP vs MAP')
    ax.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_WKB_eyring_rates_fwd.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_WKB_eyring_rates_fwd.png")

    # (2) Reverse: MEP vs MAP
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.semilogy(inv_T, kr_mep_arr, color='#c85000', lw=2,
                label=r'$k_r$ MEP')
    ax.semilogy(inv_T, kr_inst_arr, color='#2ca02c', lw=2, ls='--',
                label=r'$k_r$ MAP')
    ax.axvline(1000.0 / T_REPORT, color='gray', lw=0.8, ls=':',
               label=f'T = {T_REPORT:.0f} K')
    ax.set_xlabel('1000 / T  (K⁻¹)')
    ax.set_ylabel('Rate constant  (s⁻¹)')
    ax.set_title('Reverse Eyring rates: MEP vs MAP')
    ax.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_WKB_eyring_rates_rev.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_WKB_eyring_rates_rev.png")

    # --------------------------------------------------------
    # MEP vs MAP paths plot
    # --------------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 7))
    levels = np.linspace(0, min(np.max(energies_raw), 2.0), 30)
    contour = ax.contourf(D1, D2, energies_raw, levels=levels, cmap='viridis')
    ax.contour(D1, D2, energies_raw, levels=levels, colors='black',
               linewidths=0.3, alpha=0.5)
    ax.plot(mep_path[:, 0], mep_path[:, 1], 'r-', lw=2.5, label='MEP')

    if inst_path_f is not None:
        ax.plot(inst_path_f[:, 0], inst_path_f[:, 1], 'w--', lw=2.5,
                label=f'MAP fwd (dev={inst_curv_f:.3f} Å)')
        if inst_nodes_f is not None:
            ax.plot(inst_nodes_f[:, 0], inst_nodes_f[:, 1], 'wo',
                    markersize=4, alpha=0.7)

    if inst_path_r is not None:
        ax.plot(inst_path_r[:, 0], inst_path_r[:, 1], 'c:', lw=2.5,
                label=f'MAP rev (dev={inst_curv_r:.3f} Å)')
        if inst_nodes_r is not None:
            ax.plot(inst_nodes_r[:, 0], inst_nodes_r[:, 1], 'c^',
                    markersize=4, alpha=0.7)

    ax.plot(canonical_pos[0], canonical_pos[1], 'w*', markersize=12,
            label='Canonical')
    ax.plot(tautomeric_pos[0], tautomeric_pos[1], 'r*', markersize=12,
            label='Tautomeric')
    ax.plot(saddle_pos[0], saddle_pos[1], 'y*', markersize=15,
            label='Saddle point')
    plt.colorbar(contour, ax=ax, label='Energy (eV)')
    ax.set_xlabel(r'$d_1$ (Å)')
    ax.set_ylabel(r'$d_2$ (Å)')
    ax.set_title('MEP vs MAP paths (forward and reverse)')
    ax.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_mep_vs_MAP.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_mep_vs_MAP.png")

    # --------------------------------------------------------
    # Energy profiles: MEP vs both MAP paths
    # --------------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.plot(mep_arc, mep_energies_rel, 'r-', lw=2, label='MEP')

    if inst_path_f is not None:
        inst_en_f = np.array([get_energy(spline, p[0], p[1])
                              for p in inst_path_f])
        inst_en_f_rel = inst_en_f - E_ref
        inst_seg_f = np.sqrt(np.sum(np.diff(inst_path_f, axis=0)**2, axis=1))
        inst_arc_f = np.concatenate([[0], np.cumsum(inst_seg_f)])
        ax.plot(inst_arc_f, inst_en_f_rel, 'b--', lw=2, label='MAP fwd')

    if inst_path_r is not None:
        inst_en_r = np.array([get_energy(spline, p[0], p[1])
                              for p in inst_path_r])
        inst_en_r_rel = inst_en_r - E_ref
        inst_seg_r = np.sqrt(np.sum(np.diff(inst_path_r, axis=0)**2, axis=1))
        inst_arc_r = np.concatenate([[0], np.cumsum(inst_seg_r)])
        ax.plot(inst_arc_r, inst_en_r_rel, 'g:', lw=2, label='MAP rev')

    ax.axhline(0, color='gray', lw=0.5, ls='-')
    ax.axhline(mep_final_DV1, color='#c85000', lw=0.8, ls=':',
               label=f'ΔV₁(MEP) = {mep_final_DV1:.3f} eV')
    ax.axhline(inst_DV1, color='#0055c8', lw=0.8, ls=':',
               label=f'ΔV₁(MAP) = {inst_DV1:.3f} eV')
    ax.set_xlabel('Path Length (Å)')
    ax.set_ylabel('Energy (eV)')
    ax.set_title('Energy profile: MEP vs MAP (forward and reverse)')
    ax.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(f'{grid_dir}/2d_energy_mep_vs_MAP.png', dpi=150)
    plt.close()
    print(f"Saved: {grid_dir}/2d_energy_mep_vs_MAP.png")

    # --------------------------------------------------------
    # CSV
    # --------------------------------------------------------
    df = pd.DataFrame({
        'T_K': T_arr,
        'kappa_MEP_f': kap_mep_f_arr,
        'kappa_MEP_r': kap_mep_r_arr,
        'k_f_MEP': kf_mep_arr,
        'k_r_MEP': kr_mep_arr,
        'kappa_map_f': kap_inst_f_arr,
        'kappa_map_r': kap_inst_r_arr,
        'k_f_map': kf_inst_arr,
        'k_r_map': kr_inst_arr,
    })
    df.to_csv(f'{grid_dir}/2d_WKB_rates_vs_temperature.csv',
              index=False, float_format='%.6e')
    print(f"Saved: {grid_dir}/2d_WKB_rates_vs_temperature.csv")

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------
    print(f"\n{'='*60}")
    print(f"  SUMMARY")
    print(f"{'='*60}")
    print(f"  Canonical min at:  ({canonical_pos[0]:.3f}, {canonical_pos[1]:.3f}) Å")
    print(f"  Tautomeric min at: ({tautomeric_pos[0]:.3f}, {tautomeric_pos[1]:.3f}) Å")
    print(f"  Saddle point at:   ({saddle_pos[0]:.3f}, {saddle_pos[1]:.3f}) Å")
    print(f"\n  MEP barriers:")
    print(f"    Forward barrier:   {mep_final_DV1:.4f} eV")
    print(f"    Reverse barrier:   {mep_final_DV2:.4f} eV")
    print(f"  MAP barriers:")
    print(f"    Forward barrier (MAP_f): {inst_DV1:.4f} eV")
    print(f"    Reverse barrier (MAP_r): {inst_DV2:.4f} eV")
    print(f"  Asymmetry:         {DE:.4f} eV")
    print(f"  MAP nodes:   {n_inst_nodes}")
    print(f"  MAP fwd curvature: {inst_curv_f:.4f} Å")
    print(f"  MAP rev curvature: {inst_curv_r:.4f} Å")
    print(f"  Mean path separation: {path_diff:.4f} Å")
    print(f"  MAP fwd SCF converged: {inst_conv_f}")
    print(f"  MAP rev SCF converged: {inst_conv_r}")
    print(f"\n  κ_MEP(fwd) at {T_REPORT:.1f} K:    {kappa_mep_f:.4f}")
    print(f"  κ_MEP(rev) at {T_REPORT:.1f} K:    {kappa_mep_r:.4f}")
    print(f"  κ_MAP(fwd) at {T_REPORT:.1f} K:    {kappa_inst_f:.4f}")
    print(f"  κ_MAP(rev) at {T_REPORT:.1f} K:    {kappa_inst_r:.4f}")
    print(f"\n  τ_f (MEP):         {1/k_f_mep:.4e} s")
    print(f"  τ_r (MEP):         {1/k_r_mep:.4e} s")
    print(f"  τ_f (MAP):   {1/k_f_inst:.4e} s")
    print(f"  τ_r (MAP):   {1/k_r_inst:.4e} s")
    if n_workers > 1:
        print(f"\n  Parallelisation: {n_workers} workers")
    print(f"{'='*60}")

    print(f"\n  If you used this script or found it helpful, please cite:")
    print(f"  Authors, \"Your Paper Title\",")
    print(f"  Manuscript in preparation (2026).")
    print(f"")


if __name__ == '__main__':
    main()
